### PR TITLE
Ensure `Data` export methods return correct type

### LINKED ISSUE #2756: little bug in _prepare_gnuplot
The second last line of the function _prepare_gnuplot in orm/nodes/data/array/bands.py is:
extra_files = {dat_filename: raw_data.encode('utf-8')}
However raw_data is already "bytes" object as it comes from _prepare_dat_blocks where .encode('utf-8') is applied to the returning string. So AttributeError: 'bytes' object has no attribute 'encode' is risen when the function is called.
Solution is to remove one of the two .encode('utf-8'), but I don't know which one is better...

### LINKED ISSUE #3277: `verdi data cif show {CifData}` not working in aiida-1.0.0b5
As shown in the example, a correct CifData fails to show (`-F jmol` and `-F vesta` give similar errors).

```
$verdi data cif content 7755
data_crystal
_audit_creation_method AiiDA-ddec_plugin 
 
_cell_length_a    4.00001
_cell_length_b    5.52648
_cell_length_c    4.59630
_cell_angle_alpha 90.00000
_cell_angle_beta  90.00000
_cell_angle_gamma 90.00000
 
_symmetry_space_group_name_Hall 'P 1'
_symmetry_space_group_name_H-M  'P 1'
 
loop_
_symmetry_equiv_pos_as_xyz
 'x,y,z' 
 
loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_charge
O          O       0.50000   0.50000   0.56487  -0.77829
H          H       0.50000   0.63811   0.43513   0.38914
H          H       0.50000   0.36189   0.43513   0.38915

$ verdi data cif show 7726
Traceback (most recent call last):
  File "/home/daniele/anaconda3/envs/aiida1/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/site-packages/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/site-packages/aiida/cmdline/commands/cmd_data/cmd_cif.py", line 87, in cif_show
    show_function(fmt, data)
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/site-packages/aiida/cmdline/commands/cmd_data/cmd_show.py", line 63, in _show_jmol
    tmpf.write(trajectory._exportcontent('cif', **kwargs)[0])
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/tempfile.py", line 485, in func_wrapper
    return func(*args, **kwargs)
TypeError: write() argument must be str, not bytes
```

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #2756 and fixes #3277 

Sub classes of `Data` can implement methods that export their content in
a certain format. The `Data.export` function will call through to these
sub class specific methods and expects the returned content to be a
byte string. This was not always the case and so caused exceptions. A
test is added that checks the type of the returned tuple for the `Data`
sub classes that currently have export functionality.

The `verdi data * show/export` commands that serve as a CLI endpoint for
this export functionality will have to make sure that if they need to
write the returned export content to file, that they open the target in
binary mode. This was not the case for all formats and is now fixed.

### CODE REVIEW

**Comment by giovannipizzi** [comment]
While I check it:
- Does it also fix #2462?
- Does it supersede #2838?

**Comment by sphuber** [comment]
> * Does it also fix #2462?

I doubt it, although I have not verified it. Looking at the stacktrace reported in that issue though it seems to be unrelated. I explained why I think that in the issue itself

> * Does it supersede #2838?

Partially, but it doesn't address #2462 but then again PR #2838 would have neither. Finally Sasha's PR removes the `from __future__ import print` statement from the template file that is generated. I don't know how that was related to any of those reported issues and it was not explained so I did not include it.

File: aiida/backends/tests/orm/data/test_data.py [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    def test_data_exporters(self):
+        """Test the export functions for various data classes that should return content as bytes.
+
+        Note that the list of `Data` sub classes over which we loop is created manually here. If there are `Data`
+        classes that have export functionality that are not listed yet, they will not be tested. So they should be
+        added to the list manually.
+        """
+        for data_class in (orm.CifData, orm.StructureData, orm.BandsData, orm.TrajectoryData):
+
+            instance = self.generate_class_instance(data_class)
```
[the remark this answers is not in the document]
Comment (sphuber) [reply aiida/backends/tests/orm/data/test_data.py]: yes, that seems like a good idea, since we can only test internal entry points anyway. The tests are broken due to #3412 again, but I think I have found the source, so I will make a separate PR for that
