### ISSUE TITLE
`verdi process kill` raises `ImportError`

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#7309]
### Describe the bug

```python
❮ verdi process kill 35136
Report: Request to kill Process<35136> sent.
Report: Waiting for process(es) 35136.
Report: Request to kill Process<35136> processed.
Exception ignored in: <function RabbitmqBroker.__del__ at 0x10165af80>
Traceback (most recent call last):
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/brokers/rabbitmq/broker.py", line 52, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
```

### Your environment

- Operating system [e.g. Linux]: MacOS
- Python version [e.g. 3.7.1]: 3.10.20
- aiida-core version [e.g. 1.2.1]: 15454cd9f9e35f91c60a61ec0a009de571a2650c
- RabbitMQ: 4.2.5

@agoscinski pretty sure this is caused by 46b6f6624. A hard reset to the previous commit (26c1c6c14) resolves the problem.

**Comment by agoscinski** [comment]
Thanks for the issue. Really useful to have some feedback on this change.

The problem is if `__del__` is triggered during a shutdown, then one cannot import anymore warnings. Subsequently when this is fixed during a shutdown we get different resource issues
```
     Exception ignored in: <function RabbitmqBroker.__del__ at 0x101a01e40>
     Traceback (most recent call last):
       File "/Users/alexgo/code/aiida-core/fix-del-broker/src/aiida/brokers/rabbitmq/broker.py", line 54, in __del__
       File "/Users/alexgo/code/aiida-core/fix-del-broker/src/aiida/brokers/rabbitmq/broker.py", line 48, in close
       File "/Users/alexgo/code/aiida-core/.pixi/envs/default/lib/python3.11/site-packages/kiwipy/rmq/threadcomms.py", line 169, in close
       File "/Users/alexgo/code/aiida-core/.pixi/envs/default/lib/python3.11/site-packages/pytray/aiothreads.py", line 165, in await_
     AttributeError: 'NoneType' object has no attribute 'futures'
```
Its because the asyncio resources are already released and for a close we need the event loop. In this case I would just skip the closing during a shutdown which one can check with `sys.is_finalizing`.

Another problem I realized when fixing it is that the warning becomes silent. It seems that the logging system of Python suppresses resource warnings by default. I am trying to understand if we can at leas make this available in some developer mode since I can understand that we do not want to expose this to users.

**Comment by agoscinski** [comment]
So python still shows resource warnings with the `PYTHONDEVMODE=1`. Note that 603ff37a0b added a filter of warnings that suppresses them. We need to scope this properly.
