### PR TITLE
Extract `Model` classes out of ORM entity classes

### PR DESCRIPTION
**Pull request by edan-bainglass**
This PR extracts the nested ORM entity models out to the module level for consistency. It builds on the work of #6255 and #6990. Similar to what was done in #5183 for collections.

The of this PR is as follows (referencing the example below):
1. It lifts the nested model to the module level and properly names it with the corresponding entity prefix
2. It adds a `Model` class attribute as a type alias for the module-level model

2 ensures that much of the existing model mechanics are retained while avoiding the nested model.

### Before
```python
class SomeEntity(SomeBase):
   class Model(SomeBase.Model):
      ...
```
### After
```python
class SomeEntityModel(SomeBaseModel):
   ...

class SomeEntity(SomeBase):
   Model: TypeAlias = SomeEntityModel
```

### Why do this?

I found it difficult type hinting for the nested model system. I had hoped that providing the model at the module level will resolve this matter, for example, by allowing the definition of `EntityModelType = TypeVar('EntityModelType', bound=EntityModel)`, instead of binding it to `Entity.Model`, which seemed to not work with `mypy`.

It ended up being a bit of a typing hell. However, I am uncertain if it is due to the design or a misunderstanding of typing on my part. Help welcomed @danielhollas 🙏

### CODE REVIEW

File: src/aiida/common/typing.py [hunk 1]
```diff
@@ -19,6 +19,11 @@
 else:
     from typing_extensions import Self
 
-__all__ = ('FilePath', 'Self')
+if sys.version_info >= (3, 10):
+    from typing import TypeAlias
+else:
+    from typing_extensions import TypeAlias
```
Comment (edan-bainglass) [inline src/aiida/common/typing.py]: @danielhollas you do this in #7036 in age_entities.py. Moving it here for consistency.

File: src/aiida/orm/authinfos.py [hunk 2]
```diff
@@ -29,7 +30,7 @@
 __all__ = ('AuthInfo',)
 
 
-class AuthInfoCollection(entities.Collection['AuthInfo']):
+class AuthInfoCollection(entities.EntityCollection['AuthInfo']):
```
Comment (edan-bainglass) [inline src/aiida/orm/authinfos.py]: Renamed for clarity/consistency

File: src/aiida/orm/authinfos.py [hunk 3]
```diff
@@ -44,40 +45,44 @@ def delete(self, pk: int) -> None:
         self._backend.authinfos.delete(pk)
 
 
+class AuthInfoModel(entities.Entity.Model):
```
Comment (edan-bainglass) [inline src/aiida/orm/authinfos.py]: As mentioned in the PR description, I provided the `Model` attribute (see below) to allow retaining `Entity.Model` access. However, this required me to define it as a `TypeAlias` (which is recommended by PEP). But it is unclear to me if this is correct, or rather if this helps with typing. More on this in entities.py.

File: src/aiida/orm/entities.py [hunk 4]
```diff
@@ -179,83 +178,76 @@ def count(self, filters: Optional['FilterType'] = None) -> int:
...
+        decorators.field_validators = _prune_field_decorators(decorators.field_validators)
+        decorators.field_serializers = _prune_field_decorators(decorators.field_serializers)
+
+        return InputModel
+
+
+class Entity(abc.ABC, Generic[BackendEntityType, EntityCollectionType], metaclass=EntityFieldMeta):
+    """An AiiDA entity"""
+
+    Model: TypeAlias = EntityModel
```
Comment (edan-bainglass) [inline src/aiida/orm/entities.py]: As promised, more on `EntityModelType`...

Here I initially tried to add an `EntityModelType` to the `Generic` list on `Entity` and wire it throughout `Entity`, for example, `Model: type[EntityModelType] = EntityModel`. But this did not yield the desired outcome. Again, it may just be due to a misunderstanding of typing on my part. @danielhollas great if we can discuss this.

File: src/aiida/orm/nodes/data/array/trajectory.py [hunk 5]
```diff
@@ -104,7 +108,7 @@ def _internal_validate(self, stepids, cells, symbols, positions, times, velociti
         numatoms = len(symbols)
         if positions.shape != (numsteps, numatoms, 3):
             raise ValueError(
-                'TrajectoryData.positions must have shape (s,n,3), ' 'with s=number of steps and n=number of symbols'
+                'TrajectoryData.positions must have shape (s,n,3), with s=number of steps and n=number of symbols'
```
Comment (edan-bainglass) [inline src/aiida/orm/nodes/data/array/trajectory.py]: Unrelated formatting (a few more later)

File: src/aiida/orm/nodes/data/array/bands.py [hunk 6]
```diff
@@ -143,7 +144,7 @@ def nint(num):
                 lumo = [_[0][_[1] + 1] for _ in zip(bands, homo_indexes)]
             except IndexError:
                 raise ValueError(
-                    'To understand if it is a metal or insulator, ' 'need more bands than n_band=number_electrons'
+                    'To understand if it is a metal or insulator, need more bands than n_band=number_electrons'
```
Comment (edan-bainglass) [inline src/aiida/orm/nodes/data/array/bands.py:146]: Unrelated formatting (a few more later)

File: src/aiida/orm/nodes/node.py [hunk 7]
```diff
@@ -372,7 +380,7 @@ def __init__(
             self.base.extras.set_many(extras)
 
     @classmethod
-    def from_model(cls, model: Model) -> Self:  # type: ignore[override]
+    def from_model(cls, model: NodeModel) -> Self:  # type: ignore[override]
```
Comment (edan-bainglass) [inline src/aiida/orm/nodes/node.py:364]: Unclear why `mypy` complains. `NodeModel` is a subclass of `EntityModel`. But I imagine here I'm misunderstanding typing/subtyping, etc. @danielhollas what do you think?

File: src/aiida/common/typing.py (hunk 1 above)
Comment (danielhollas) [reply src/aiida/common/typing.py]: I've opened #7096 as a better solution for this. I don't think it makes sense to put these common types in our own module.

File: src/aiida/orm/authinfos.py (hunk 3 above)
Comment (danielhollas) [reply src/aiida/orm/authinfos.py]: Which PEP do you mean?

EDIT: In this specific files, if I remove the `TypeAlias` annotation it still type-checks. So I don't think it's needed here?
(also it seems very weird for it to be TypeAlias, it's a (generic) class?

**Comment by danielhollas** [comment]
> 'm trying to make this one work, but it seems to require a lot of typing tweaks. 

I'll have a look once I am back but no promises as this seem to touch on the generics / variance topics which are still very murky to me.

> Anyhow, it would be easier to understand for a reviewer if and when https://github.com/aiidateam/aiida-core/pull/6990 is merged.

You can push the branch from #6990 to the origin repo, and then make it a target for this PR.

>  For now, if possible, can you make sense of why the test-install tests are failing? They work locally for me, so unclear.

The job fails at the setup step, not during the tests. Have you looked into it? The error seems to suggest something is broken here, but I don't have time to dig deeper (still on holidays :sweat_smile:)

File: src/aiida/orm/authinfos.py (hunk 3 above)
Comment (edan-bainglass) [reply src/aiida/orm/authinfos.py]: Sorry, not PEP, but `mypy` - see https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases. However, this is not quite correct. The recommendation is that the class variable `Model` should be explicitly typed as a `TypeAlias`, as compared to global variables. In any case, I don't care for this solution in general. I don't think `TypeAlias` is the correct approach, but I'm uncertain about all of this.

File: src/aiida/common/typing.py (hunk 1 above)
Comment (edan-bainglass) [reply src/aiida/common/typing.py]: Well, it makes sense if the try...except dance (as you call it) is required, to avoid excessive dancing 😅 I think in #7096 your claim is that the dance itself is not required.

File: src/aiida/orm/authinfos.py (hunk 3 above)
Comment (edan-bainglass) [reply src/aiida/orm/authinfos.py]: I'm not sure if it is good to inherit from a class property reference. However, I encounter strange behavior from pydantic when I expose the model classes directly. I'll paste the error here shortly.

Comment (edan-bainglass) [reply src/aiida/orm/authinfos.py]: Right, so after switching from `Entity.Model` to `EntityModel`, etc. in the inheritance chain `Entity -> Node -> Data -> AbstractCode -> InstalledCode`, I get the following `mypy` error

```
(aiida-dev) (refactor-models) aiida-core > mypy src/aiida/orm/nodes/data/code/
src/aiida/orm/nodes/data/code/installed.py:38: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.18.2
Traceback (most recent call last):
  File "mypy/semanal.py", line 7350, in accept
  File "mypy/nodes.py", line 1440, in accept
  File "mypy/semanal.py", line 1775, in visit_class_def
  File "mypy/semanal.py", line 1991, in analyze_class
  File "mypy/semanal.py", line 2038, in analyze_class_body_common
  File "mypy/semanal.py", line 2123, in apply_class_plugin_hooks
  File "/home/edanb/miniforge3/envs/aiida-dev/lib/python3.10/site-packages/pydantic/mypy.py", line 184, in _pydantic_model_class_maker_callback
    return transformer.transform()
  File "/home/edanb/miniforge3/envs/aiida-dev/lib/python3.10/site-packages/pydantic/mypy.py", line 518, in transform
    fields, class_vars = self.collect_fields_and_class_vars(config, is_root_model)
  File "/home/edanb/miniforge3/envs/aiida-dev/lib/python3.10/site-packages/pydantic/mypy.py", line 682, in collect_fields_and_class_vars
    self._api.fail(
  File "mypy/semanal.py", line 7325, in fail
AttributeError: attribute 'column' of 'Context' undefined
src/aiida/orm/nodes/data/code/installed.py:38: : note: use --pdb to drop into pdb
```
I have not yet attempted further debugging.

Notice that this is an apparent issue of the pydantic mypy plugin, which you recently introduced in #7064. Indeed, disabling the plugin removes the error.

Comment (danielhollas) [reply src/aiida/orm/authinfos.py]: Oof, we're getting into some dark magic territory. Maybe if you managed to get a minimal reproducer you could open a bug report against pydantic? Internal error seems like something that's not your fault.

(I don't really care about the plugin, I hoped it would be helpful,  but we can remove it if it would conflict with this PR)

Btw: this discussion seems relevant
https://github.com/python/typing/discussions/1424

Edit: also this?
https://github.com/python/mypy/issues/11538#issuecomment-980429121

**Comment by edan-bainglass** [comment]
> > For now, if possible, can you make sense of why the test-install tests are failing? They work locally for me, so unclear.
> 
> The job fails at the setup step, not during the tests. Have you looked into it? The error seems to suggest something is broken here, but I don't have time to dig deeper (still on holidays 😅)

It seems to fail at `verdi code create core.code.installed --non-interactive --config "${CONFIG}/doubler.yaml"`, which runs fine locally. No worries. Enjoy your vacay 😎
