### PR TITLE
CLI: Fix exception for `verdi plugin list`

### LINKED ISSUE #6557: CLI:  `verdi plugin list` fails for data plugins
@edan-bainglass encountered the following issue and I've quickly investigated it.

Running e.g. `verdi plugin list aiida.data core.array` causes an exception:

```
verdi plugin list aiida.data core.array
Traceback (most recent call last):
  File "/Users/treents/.aiida_venvs/dev_aiida_core/bin/verdi", line 8, in <module>
    sys.exit(verdi())
             ^^^^^^^
  File "/Users/treents/.aiida_venvs/dev_aiida_core/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/treents/.aiida_venvs/dev_aiida_core/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/treents/.aiida_venvs/dev_aiida_core/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/treents/.aiida_venvs/dev_aiida_core/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/treents/.aiida_venvs/dev_aiida_core/lib/python3.11/site-packages/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/treents/.aiida_venvs/dev_aiida_core/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/treents/.aiida_venvs/dev_aiida_core/lib/python3.11/site-packages/aiida/cmdline/commands/cmd_plugin.py", line 56, in plugin_list
    echo.echo(str(plugin.get_description()))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Node.get_description() missing 1 required positional argument: 'self'
```

This error was introduced in #6411. In previous versions, e.g. `aiida-core 2.5`, the command would simply print the error:
```Error: No description available for core.array```

Due to the changes in the aforementioned PR #6411, the `try except` is not triggered. As no `AttributeError` is raised anymore after adding the `hasattr(plugin, 'is_process_function')`:
https://github.com/aiidateam/aiida-core/blob/fb3686271fcdeb5506838a5a3069955546b05460/src/aiida/cmdline/commands/cmd_plugin.py#L50-L58

Since the `hasattr` simply returns `False` in case of the `ArrayData`, the `else` statement is executed. Here, the error shown above is raised, as `plugin.get_description()` tries to call `get_description` on the class and not on an object. However, `get_description` is not a class method in `orm.Node`, leading to the exception.

Without thinking too much about it, one possible fix would be to create an object, i.e. calling `plugin().get_description()` (this would work for methods and class methods). However, I'm not sure if this will cause additional problems. 
Furthermore, one could catch the `TypeError` in the `except` statement as well. Again, these were just some ideas that came to my mind. There might be more things to consider that could lead to different solutions.

Pinging @sphuber and @khsrali who have worked on the previous PR.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #6557 

In e952d7717c1d8001555e8d19f54f4fa349da6c6e a bug in `verdi plugin list` was fixed where the conditional to check whether the plugin was a process class would always raise an `AttributeError` if the plugin was not a `Process` or a proces function. As a result, the code would never get to the else-clause.

The else-clause contained itself another bug, which was now revealed by the fixing of the bug in the conditional. The else-clause would call the `get_description` classmethod of the plugin, but no classes in AiiDA that are pluginnable even define such a class method. Probably, the original author confused it with the instance method `get_description` but the `verdi plugin list` command just deals with the class.

The `get_description` call is replaced with just getting `__doc__` which returns the docstring of the class/function, or `None` if it is not defined. In the latter case, a default message is displayed saying that no description is available.

Since the else-clause code was never reached before the recent fix and the `get_description` method was never supported officially by AiiDA's pluginnable interfaces, it is fine to just change this behavior.

### CODE REVIEW

**Review by khsrali — APPROVED** [review]
Thanks, @sphuber. 
Changes make sense; the only thing is backward compatibility for plugins that have their description stored in 'get_description()' as a classmethod. 

But since this is only a description, I think it's fine.

**Comment by sphuber** [comment]
> Thanks, @sphuber. Changes make sense; the only thing is backward compatibility for plugins that have their description stored in 'get_description()' as a classmethod.

Which plugins would have this though? This has never been part of any plugin API. There are no classes in AiiDA that have the `get_description` class method as part of their interface. It was just a mistake in `verdi plugin list` that wasn't even ever hit because of the other bug.

**Comment by khsrali** [comment]
> Which plugins would have this though? This has never been part of any plugin API. There are no classes in AiiDA that have the `get_description` class method as part of their interface. It was just a mistake in `verdi plugin list` that wasn't even ever hit because of the other bug.

`aiida-firecrest` was doing it that way, simply because of the way `plugin_list()` was written we thought that's the way.

Of course this would be an easy change for us.
Just saying that there might be other plugins out there that thought the same.

**Comment by sphuber** [comment]
> `aiida-firecrest` was doing it that way, simply because of the way `plugin_list()` was written we thought that's the way.

Ah I see, well in that case I think it is fine as you say. Thanks for the review
