### ISSUE TITLE
Tests should check that daemon can be restarted without errors in the log

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4667]
@mbercx and I seem to be having `TIMEOUTS` when restarting or stopping the daemon. It does stop in both cases, and it succeeds when manually `verdi daemon start`ing it:

```
$ verdi daemon stop 
Profile: charge_density
Waiting for the daemon to shut down... TIMEOUT
$ verdi daemon start
Starting the daemon... RUNNING
$ verdi daemon restart 
Restarting the daemon... TIMEOUT
$ verdi daemon status
Profile: charge_density
The daemon is not running
$ verdi daemon start
Starting the daemon... RUNNING
```

We checked our logs and found similar error reports:

```
Exception in callback start_daemon.<locals>.<lambda>() at /home/framirez/Workgit/aiida-core/aiida/engine/daemon/runner.py:59
handle: <Handle start_daemon.<locals>.<lambda>() at /home/framirez/Workgit/aiida-core/aiida/engine/daemon/runner.py:59>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/framirez/Workgit/aiida-core/aiida/engine/daemon/runner.py", line 59, in <lambda>
    runner.loop.add_signal_handler(s, lambda s=s: asyncio.create_task(shutdown_runner(runner)))
AttributeError: module 'asyncio' has no attribute 'create_task'
```

@mbercx initially reported this behaviour in issue #4648 because it seemed related (see comment [here](https://github.com/aiidateam/aiida-core/issues/4648#issuecomment-762390990)) but apparently the error in the logs is different.

In principle this doesn't seem to come out in a clean environment. We can keep trying to see if we manage to reproduce it there, but hopefully this log gives an idea of what may be happening @sphuber @unkcpz?

**Comment by ltalirz** [comment]
@ramirezfranciscof Thanks for reporting this together with the error log. 

Since the top-level `create_task` function [was introduced only on python 3.7](https://stackoverflow.com/a/53247626/1069467),  this indicates to me you are running python 3.6 - can you confirm?

January 13th 2021 [marks the end of python 3.6 support in AiiDA](https://www.aiida.net/download/); @csadorf is already working on officially dropping  3.6](https://github.com/aiidateam/aiida-core/issues/4691). I believe this will resolve the original reported issue.

However, this leaves the question why this was not caught in the tests up to now (which did run on python 3.6).

While we do test starting the daemon and running calculations
https://github.com/aiidateam/aiida-core/blob/97cecd2ef57946dd53a0ecd2005f3d2d0a94a2aa/.github/workflows/tests.sh#L20-L23
there is no check on the logs, i.e. I guess this issue could go undetected.

@sphuber @chrisjsewell do you see a straightforward way how this could be captured?
Should we open another issue for adding support for a daemon mode that would "die on exception" (rather than logging it)?

**Comment by ramirezfranciscof** [comment]
Thanks @ltalirz ! Indeed this was the case, I installed python3.9 and created a new virtual environment and it seems to work fine here. Will leave the issue open to discuss the possibility of testing for the error you propose.

**Comment by mbercx** [comment]
Indeed, when I encountered the error with the above error log, this was in a test environment using Python 3.6. I also reproduced the timeout issue using Python 3.7.9 (in a Quantum Mobile container), but in this case the error in the logs was that reported in #4648, and the processes `Excepted`.

**Comment by chrisjsewell** [comment]
Hey guys check out #4769, would appreciate some feedback

**Comment by sphuber** [comment]
When you call `verdi daemon stop`, the circus daemon sends the kill message to all workers, which in turn will try to cleanly stop what they are doing before shutting down. However, if they are busy, they might need more time and not stop in time, and so circus will just hard kill them and return the `TIMEOUT` error.

To be honest, I am not sure what the best behavior would be here. If people find the timeout confusing, then the only solution is to not give the workers a grace period to shutdown but to simply kill them a.s.a.p. and not wait. With the checkpointing system in principle no work should be lost, but with a grace period, the worker could reach a few more checkpoints, making it that less work has to be redone when the daemon starts again.

I don't think that it makes sense to test for this in the tests since it should only happen when the daemon workers are running a lot of processes and cannot shutdown in time.
